### ISSUE TITLE
Feature: Support error causes

### ISSUE THREAD

**Issue by conartist6** [tapjs/stack-utils#61]
This is a proposal to support printing stacks of errors nested with `error.cause`. The JS spec allows `error.cause` to be any value, but this proposal is mainly concerned with what happens when `cause` is present as a string or another error.

I've written up the most descriptive form of this proposal as a [proposed jest feature](https://github.com/facebook/jest/issues/11935). If you don't mind I'll avoid copying it all out here. Jest uses `stack-utils` under the hood to reformat errors.

The TC39 committee has so far indicated that the language will not provide any official implementation of printing nested errors. Their hands are tied to some extent until they finish specifying the semantics of `error.stack`. But until then it will be very useful to have best-effort printing and formatting for errors printed in the most common way.

I think errors with causes should be printed more or less like this:
```
SomeError: The grumblecakes could not be found
    at grumblecake-locator.js:12:2
Caused by: QueryError: Invalid query `SELECT <grumblecakes>`
    at db.js:51:4
Caused by: ParseError: Unexpected character `<` at position 8
    at db.js:1233:10
```

Currently there is no standard for this. I think `stack-utils` would be an excellent library in which to create an implementation which formats, prints, and loosely parses errors with multiple messages and stack traces.

I'm willing to build it. Is there interest from the maintainers?

**Comment by conartist6** [comment]
I've adapted the project's current regex into a lexer that I think will work:
```js
const moo = require("moo");

let lexer = moo.compile({
  whitespace: { match: /[ \t\n]/, lineBreaks: true },
  causedBy: /^\s*Cause(?:d by)?:/,
  // Any line ending with file:line:col is a stack frame
  // file:line:col may be wrapped in parens, or may be the literal 'native'
  stackFrame: /^.*?(?:native|:\d+:\d+|\((?:.+?:\d+:\d+|native)\))$/,
  freeText: /.+$/,
});
```

Stack frame lines would be subject to further parsing. In particular the current big stack-frame-line regex will need to be broken down in order to support embedding URI syntax and fix #60.

**Comment by conartist6** [comment]
Here's a condensed summary of the output from that lexer:
```js
[
  {
    type: 'freeText',
    text: 'SomeError: The grumblecakes could not be found',
  },
  {
    type: 'whitespace',
    text: '\n',
  },
  {
    type: 'stackFrame',
    text: 'at grumblecake-locator.js:12:2',
  },
  {
    type: 'whitespace',
    text: '\n',
  },
  {
    type: 'causedBy',
    text: 'Caused by:',
  },
  {
    type: 'whitespace',
    text: ' ',
  },
  {
    type: 'freeText',
    text: 'QueryError: Invalid query `SELECT <grumblecakes>`',
  },
  {
    type: 'whitespace',
    text: '\n',
  },
  {
    type: 'stackFrame',
    text: 'at db.js:51:4',
  },
  {
    type: 'whitespace',
    text: '\n',
  },
  {
    type: 'causedBy',
    text: 'Caused by:',
  },
  {
    type: 'whitespace',
    text: ' ',
  },
  {
    type: 'freeText',
    text: 'ParseError: Unexpected character `<` at position 8',
  },
  {
    type: 'whitespace',
    text: '\n',
  },
  {
    type: 'stackFrame',
    text: 'at db.js:1233:10',
  }
]
```

**Comment by conartist6** [comment]
Oh boy this project actually already supports "nesting" of error stacks through string concatenation as done by [nested-error-stacks](https://www.npmjs.com/package/nested-error-stacks). Unfortunately the behavior of nested-error-stacks is fundamentally not interoperable with errors that have causes. After all, to print errors stacked using cause you need access to their unstacked stack traces, which are destroyed by nested-error-stacks.

In practice it outputs the same the same `Caused by:` string that I'm now working on parsing, so the only real difference would be in printing. If `err.cause` is present, then correctness of the output relies on `err.stack` not containing the same nested traces. The good news is that nobody should be doing this. Thus it may be fine to just print everything and let it come out in the wash.

**Comment by conartist6** [comment]
Similarly I think it's probably safe to assume that most methods names won't have `()` in them. I've never seen that professionally. Of course it's trivial to create such a thing, but that doesn't mean it's not fine to have less than ideal behavior when it is encountered. Since file names are usually allowed to contain `(` and `)` and identifiers are not, I think it's likely better practice for the parser to give some mangled results when the function name contains parens. And we can soften the cases which fail: we're sure that the parens around a file name will be preceded by a space.

That would allow us to handle some pretty weird stuff without doing anything all that weird, e.g.:

```js
const obj = {
  'weird fn name()': () => {
    throw new Error('message');
  },
};

obj['weird fn name()']();
```
which results in
```
Error: message
    at Object.weird fn name() (/home/conartist6/dev/repos/stack-utils/space file.js:3:11)
    at Object.<anonymous> (/home/conartist6/dev/repos/stack-utils/space file.js:7:23)
```

**Comment by conartist6** [comment]
It may be that the easiest way to deal with this is to always tokenize parens. This will sometimes split apart parts of a single token like `Object.weird fn name()` that really belong together, but I then the parser will be able to handle balancing of parens and make the best possible effort to match the basic structure of a line (`at method (file:1:2)`), which will just leave us to find any paren tokens that were not consumed and print them back out as literals.

**Comment by conartist6** [comment]
And here's the complete parser. Try pasting it into the [nearley playground](https://omrelli.ug/nearley-playground/)
```
@{%

const lexer = moo.states({
  error: {
    CausedBy: { match: /^\s*[cC]ause(?:d [bB]y)?:/, value: () => "Caused by:" },
    At: { match: /^[ \t]*at /, push: "frame", value: () => "at " },
    Space: /[ \t]+/,
    Newline: { match: "\n", lineBreaks: true },
    // Any line ending with file:line:col is a stack frame
    // file:line:col may be wrapped in parens, or may be the literal 'native'
    Text: /.+$/,
  },
  frame: {
	CN: ":",
    LP: "(",
    RP: ")",
	Number: { match: /\d+/, value: (str) => parseInt(str, 10)},
    Newline: { match: "\n", lineBreaks: true, pop: true },
    Space: /[ \t]+/,
    FrameFragment: /[^(): \d\t\n]+/,
  },
});

%}

@lexer lexer

Error -> Message (NL Stack):? (NL CausedBy Error):? {% (d) => {
	const props = [{ message: d[0] }];
	if (d[1]) props.push({ stack: d[1][1] });
	if (d[2]) props.push({ cause: d[2][3] });
	return Object.assign({}, ...props);
}%}

Message -> Text (NL _ Text):* {% (d) => d[0] + stringFrom(d[1].flat())  %}

Text -> _Text:+ {% (d) => stringFrom(d[0]) %}

_Text -> %Text {% (d) => d[0].text %}

Stack -> Frame (NL Frame):* {% (d) => [d[0], ...(d[1] ? d[1].map(d => d[1]) : [])] %}

Frame -> At FrameFragments _ LP FrameFragments CN Number CN Number RP {% (d) => ({ function: d[1], file: d[4], line: d[6], col: d[8] }) %}
	| At FrameFragments CN Number CN Number {% (d) => ({ function: undefined, file: d[1], line: d[3], col: d[5] }) %}


FrameFragments -> (FrameFragment | CN | LP | RP | _ ):* {% (d) => stringFrom(d[0].flat()) %}

FrameFragment -> %FrameFragment {% (d) => d[0].text %}

Number -> %Number {% (d) => d[0].value %}

At -> %At _:? {% () => null %}

CausedBy -> %CausedBy _ {% () => null %}

CN -> %CN {% (d) => d[0].text %} # Colon `:`

LP -> %LP {% (d) => d[0].text %} # Left paren `(`

RP -> %RP {% (d) => d[0].text %} # Right paren `}`

NL -> %Newline {% (d) => d[0].text %}

_ -> %Space {% (d) => d[0].value  %}

@{%

function stringFrom(iterable) {
  let str = '';
  for (const f of iterable) {
    str += f;
  }
  return str;
}

%}
```

**Comment by conartist6** [comment]
Aight I'm out for the day. Signing off. No more work. Thanks for your help everyone! Errors are gonna be great!

**Comment by conartist6** [comment]
I think what this means is that I need two parsers, one for errors, and one for lines. That way the line parser can be ambiguous by design but for each line we'll eliminate any ongoing ambiguity.

The only question is how much overlap should there be? If stack lines are any lines that begin with `at `, there need be little overlap. But if we aim to support stacks were the at prefixes have been stripped away then we need to keep enough of the frame parsing to identify (file:line:col) at the end -- something we already know we are able to do unambiguously.

**Comment by conartist6** [comment]
The new `parseFrame` now passes the old test for `parseLine`. I see that in addition to nested-error-stacks, there is more general support for freetext frames such as
```
Error:
    at outer (produce-long-stack-traces.js:7:27)
From previous event:
    at Object.<anonymous> (produce-long-stack-traces.js:6:36)
```
My initial idea was to parse into a structure like this:
```ts
type StackFrame = {
    type: 'Frame';
    file: string;
    function?: string;
    // ...
  } | {
    type: 'Text';
    text: string;
  };

type ParsedError =  {
  name: string;
  message: string;
  stack: Array<StackFrame>;
  cause: ParsedError;
};
```
The weird thing with this design is that causes are from a syntactic perspective a subset of freetext stack frames, yet this structure treats them in completely different ways. The other drawback is that it's actually fairly valuable I think to have the ability to reverse iterate the cause stack, i.e. going from most specific to least specific as error handling does in real code. Essentially chaining cause through a `cause` property is creating a singly linked list, where an array would more easily permit reverse iteration.

If I do use an array I'd probably need a new type to store it in. I'd have something like:
```ts
type ErrorChain = {
  chain: Array<Error>;
};

type Error = {
  name: string;
  message: string;
  stack: Array<StackFrame>;
  isCause: boolean;
};
```

This could work much better because there'd be no more need for "freetext frames". Instead the freetext would just become the message in a new error, and the stack would always be guaranteed to be an array of frames, which seems useful from the perspective of writing code to filter out spurious frames.

I think the combined advantages of the chain approach are worth making it my new design.

**Comment by conartist6** [comment]
I've added tests which validate that I don't fall out of the strict parser's grammar for frames that don't do anything weird. It's already caught some issues. To be able to write the test I had to introduce a `strict` option to parse, which seems like probably a good idea anyway.

**Comment by conartist6** [comment]
Oh god I'm testing my work on stack-utils using AVA which formats its errors with stack-utils. I tried to stop the test on an uncaught exception and I was confused as to why the failing code was dealing with stack-utils but it didn't seem to be the one I was working on. In fact I've just discovered yet another deficiency in the current stack-utils: it can't parse the frame `at async Promise.all (index 0)` which is making its own test runner blow up. >_<

**Comment by conartist6** [comment]
I can't figure out if the first `eval` in a frame that reads`    at eval (eval at ...` is ever any text other than `eval`. I don't see any counterexamples, and without any I don't know what to call it.

**Comment by conartist6** [comment]
It has come to my attention that this is a parser for v8 stack traces, i.e. node, Chromium, Chrome, and I guess now IE Edge. I think this answers the question of what I'll do when I'm done with this work. I don't really want to have to ask permission to publish something that I wrote, but I also don't want to have to name the package something silly. So I can be `v8-stack-utils`.

**Comment by conartist6** [comment]
If you read this far I commend you! If you didn't read everything above I don't commend you, but it's OK I was just talking to myself. I started describing a feature I wanted and ended up building a whole replacement library. It's called `stack-tools`. Check it out!
